spring.application.name=AIandML


spring.application.name=demo

# DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/92r
spring.datasource.username=root
spring.datasource.password=Navinder@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# EMAIL CONFIG (GMAIL SMTP)

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=navinder10000coders@gmail.com
spring.mail.password=YOUR_GMAIL_APP_PASSWORD

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true